[
    {
        "repo_name": "pytest-dev/py",
        "CVE_ID": "CVE-2020-29651",
        "Problem_Type": "NVD-CWE-Other",
        "Description": "A denial of service via regular expression in the py.path.svnwc component of py (aka python-py) through 1.9.0 could be used by attackers to cause a compute-time denial of service attack by supplying malicious input to the blame functionality.",
        "URL": "https://github.com/pytest-dev/py/pull/257/commits/4a9017dc6199d2a564b6e4b0aa39d6d8870e4144",
        "Tag": "['Patch', 'Third Party Advisory']",
        "fix_commit_hash": "4a9017dc6199d2a564b6e4b0aa39d6d8870e4144",
        "inducing_commit_hash_pyszz": [],
        "inducing_commit_hash_pd": [
            "5992a8ef21424d7571305a8d7e2a3431ee7e1e23"
        ],
        "matched": [
            "5992a8ef21424d7571305a8d7e2a3431ee7e1e23"
        ],
        "pr_status": "merged"
    }
]